spring:
  application:
    name: hello-spring-cloud-web-admin-feign


server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Feign 是自带熔断器的，但默认是关闭的。需要在配置文件中配置打开它
# 测试熔断器可以 关闭服务提供者来测试, 然后会调用自定义方法
#
feign:
  hystrix:
    enabled: true


thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html