spring:
  application:
    name: hello-spring-cloud-web-admin-ribbon


server:
  port: 8764

#  注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html